#!/bin/bash

cat <<EOF

new -s $1  'ssh $2'
splitw -h -t 0 'ssh $4'
splitw -h -t 1 'ssh $6'

resize-pane -t 0 -L 15
resize-pane -t 1 -L 8

splitw -v -t 2 'ssh $7'
splitw -v -t 1 'ssh $5'
splitw -v -t 0 'ssh $3'





setw synchronize-panes on

EOF

